function DET=getDet3(Ixx,Ixy,Ixz,Iyy,Iyz,Izz)
%% get determinant 3*3
DET=Ixx.*Iyy.*Izz...
    +Ixy.*Iyz.*Ixz...
    +Ixz.*Ixy.*Iyz...
    -Ixz.*Iyy.*Ixz...
    -Ixy.*Ixy.*Izz...
    -Ixx.*Iyz.*Iyz;
end