function DET=getDet3_2(Ixx,Ixy,Ixz,Iyx,Iyy,Iyz,Izx,Izy,Izz)
%% get determinant 3*3
DET=Ixx.*Iyy.*Izz...
    +Ixy.*Iyz.*Izx...
    +Ixz.*Iyx.*Izy...
    -Ixz.*Iyy.*Izx...
    -Ixy.*Iyx.*Izz...
    -Ixx.*Iyz.*Izy;
end